# Generated by Django 2.0 on 2017-12-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='rol_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='rol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.roles'),
        ),
    ]
