# Generated by Django 2.0 on 2017-12-25 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='rol_id',
        ),
        migrations.AlterField(
            model_name='domains',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosting.Users'),
        ),
        migrations.DeleteModel(
            name='roles',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
