# Generated by Django 2.0 on 2017-12-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelations',
            fields=[
                ('app_user', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bd_user', models.CharField(max_length=50)),
                ('ftp_user', models.CharField(max_length=50)),
            ],
        ),
    ]
