# Generated by Django 2.0 on 2017-12-25 22:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_id', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('pg_password', models.CharField(max_length=50)),
                ('ftp_password', models.CharField(max_length=50)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now)),
                ('rol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosting.roles')),
            ],
        ),
    ]
