# Generated by Django 2.0 on 2017-12-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_roles_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelations',
            name='app_user',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
