# Generated by Django 2.0 on 2017-12-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0004_auto_20171227_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserDbUserRelation',
            fields=[
                ('app_user', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('db_user', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppUserFtpUserRelation',
            fields=[
                ('app_user', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ftp_user', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserRelations',
        ),
    ]
