# Generated by Django 2.0 on 2018-01-03 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0005_auto_20171227_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='domains',
            fields=[
                ('app_user', models.CharField(max_length=50)),
                ('domain_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='subdomains',
            fields=[
                ('subdomain_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('domain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosting.domains')),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='rol_id',
        ),
        migrations.DeleteModel(
            name='roles',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
