# Generated by Django 2.0 on 2018-01-03 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0006_auto_20180103_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='domainssubdomains',
            fields=[
                ('subdomain_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='subdomains',
            name='domain_name',
        ),
        migrations.RenameModel(
            old_name='domains',
            new_name='appuserdomains',
        ),
        migrations.DeleteModel(
            name='subdomains',
        ),
        migrations.AddField(
            model_name='domainssubdomains',
            name='domain_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosting.appuserdomains'),
        ),
    ]
