# Generated by Django 2.0 on 2018-01-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0007_auto_20180103_2016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='domainssubdomains',
            new_name='appusersubdomains',
        ),
    ]
