# Generated by Django 2.0 on 2018-01-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0008_auto_20180103_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusersubdomains',
            name='path',
            field=models.CharField(default='/', max_length=200),
        ),
    ]
